### ISSUE TITLE
RFID returning more than one user

### ISSUE THREAD

**Issue by plusk** [dotkom/regme#35]
If rfid returns more than 1 user, log as errors, remove rfid field from invalid user, and notify about the case

**Comment by sklirg** [comment]
I don't think you should do actions like that against the service. I think
the correct course of action would be to say "something went wrong, please
type your username on online.ntnu.no" and sign them in that way. Then
update their RFID. Log the case.

You [RFID app] are consuming a service, so you should so as little
destructive against it.

My 2 cents :)

**Comment by myth** [comment]
They are not going to log the errors to the application screen and notify the user. They are going to log the errors to ow4 and send us an email.

But, it will all come down to whether or not the Byggsikring guys reintroduce purged card RFIDs from users who have left the university. If that is the case, we have to have this functionality. If not, which i both hope and believe is the case, this will not have to be implemented, since we would just add a unique constraint to the field.

I only told them to add this since we just had an issue where two users somehow managed to end up with the same RFID, causing a bit of a mess. And the best time to resolve that issue would have been when the person is actually present, with the card in hand, and also potentially with an Online representative to verify. So in that regard I would not consider the application to be destructive. I would call it tidy.

**Comment by sklirg** [comment]
> They are not going to log the errors to the application screen and notify
> the user. _They are going to log the errors to ow4 and send us an email._
> That's exactly what I meant by logging the case.

Regarding "destructive", I meant that the app should probably not start
deleting things in the authentication (user profile) registry. Updating is
fine, but what happens with e.g. nibble if an RFID is deleted? I think we
should look into the case more closely and take action accordingly, rather
than allowing the app to do this automatically. And with colliding RFID
tags, there will be two parties, which not necessarily are present at the
same time.

I'm just spewing out some thoughts on the topic, if I'm all nuts, ignore me
😛

**Comment by myth** [comment]
I can see your concerns. Nothing happens to nibble. The account balance is tied to a field directly on the user object, not in any relation between RFID and user of some sort.

The main point being, RFIDs are used as a means of identification. As you say we use it for nibble as well. Hence, this shouldnt really be an issue. We should never get duplicate RFIDs. But, somehow, we did. And it took a couple of weeks before the person complaining actually got it fixed, since there is no automation of this. However, since we use it as idenfitication, one of the RFIDs had to go, and of course the person standing there with their face on the card is the rightful owner of that RFID.
There is however, a slight chance that this occured due to how cards IDs are generated, instead of what I think happened, which is fast registration during an event, maybe some eduroam issues, in combination with new cards, and the bedKom/fagKom representatives not paying enough attention to see that the system was in update-rfid mode. Next person tags along and gets rfid assigned to him/her.

But, as I said, I'm awaiting reply from the byggsikring guys. 99% likely, we add a unique constraint and close this issue.

**Comment by myth** [comment]
A solution that fallbacks to username input as you suggested (as it is today) will be a good alternative too, but if the RFID field handling on the backend is going do to nothing, we need both very verbose logs and an email.

Anyway, on second thought, the best option would be to just add the unique constraint, close this issue and if that 1% comes true, we have to open up a separate issue and have another chat.

**Comment by arwassa** [comment]
Not a regme specific issue.
